name: fastai2
channels:
- fastai
- pytorch
- defaults
dependencies:
- jupyter
- pytorch>=1.3.0
- torchvision>=0.5
- matplotlib
- pandas
- requests
- pyyaml
- fastprogress>=0.1.22
- pillow
- python>=3.6
- pip
- scikit-learn
- scipy
- spacy
- voila>=0.1.8
- ipyvuetify>=0.1.9
- voila-vuetify>=0.0.1a6
- bqplot
- numpy
